---
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.9.6
    hooks:
      # Run the linter.
      - id: ruff
        name: Lint code
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        name: Format code
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.32.0
  #   hooks:
  #     - id: yamllint
