gateways:
  duckdb:
    # For more information on configuring the connection to your execution engine, visit:
    # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connections
    # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/duckdb/#connection-options
    connection:
      type: duckdb
      register_comments: false
      catalogs:
        peoplewa:
          type: postgres
          path: 'dbname=peoplewa user=peoplewa host=localhost'
      extensions:
        - name: iceberg
    state_connection:
      type: duckdb
      database: state.db

  postgres:
    connection:
      type: postgres
      database: peoplewa
      user: peoplewa
      password: peoplewa
      host: localhost
      port: 5432


default_gateway: duckdb

model_defaults:
  dialect: duckdb
  start: 2025-05-10